I=imread('orig.tif');
J = imnoise(I,'gauss',0.02);              %添加高斯噪声
J = imnoise(I,'salt & pepper',0.02);  %(注意空格)       %添加椒盐噪声   
ave1=fspecial('average',3);              %产生3×3的均值模版
ave2=fspecial('average',5);              %产生5×5的均值模版
K = uint8(filter2(ave1,J));                 %均值滤波3×3
L = filter2(ave2,J);                 %均值滤波5×5
M = medfilt2(J,[3 3]);                  %中值滤波3×3模板
N = medfilt2(J,[4 4]);                   %中值滤波4×4模板